services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - panel_db:/var/lib/mysql
  cache:
    image: redis
    restart: always
  php-fpm: # panel, do not change name
    image: yoshiwalsh/pterodactyl-panel:v1.11.10
    restart: always
    depends_on:
      - database
    volumes:
      - panel_app:/var/www/html/
      - panel_public:/var/www/html/public/
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: cache
      TIMEZONE: ${TIMEZONE}
  nginx:
    image: yoshiwalsh/nginx-for-php-fpm
    restart: always
    depends_on:
      - php-fpm
    ports:
      - 80:80
    volumes:
      - panel_public:/var/www/html/
  pterodactyl_wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl_wings
    networks:
      - pterodactyl_network
    ports:
      - "8080:8080"
      - "2022:2022"
      # Add any other ports you need here for game servers
    depends_on:
      - php-fpm
    environment:
      - TZ=${TIMEZONE}
      - WINGS_PTERO_PANEL=${PANEL_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - panel_wings:/etc/pterodactyl
    restart: unless-stopped

volumes:
  panel_wings:
  panel_data:
  panel_public:
  panel_db:

networks:
  pterodactyl_network:
